// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA77UXx9-MgGm2yZSN-LROri9JyGjWzcCA',
    appId: '1:875046596010:ios:03c8238fae5e74167dcfd3',
    messagingSenderId: '875046596010',
    projectId: 'cinelog-2ab20',
    databaseURL: 'https://cinelog-2ab20-default-rtdb.firebaseio.com',
    storageBucket: 'cinelog-2ab20.firebasestorage.app',
    iosBundleId: 'com.example.cinelog',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGgrX-w0YmrrxIKqo3zxEs4bcHVraR0AU',
    appId: '1:875046596010:web:a4930c96993af5b77dcfd3',
    messagingSenderId: '875046596010',
    projectId: 'cinelog-2ab20',
    authDomain: 'cinelog-2ab20.firebaseapp.com',
    databaseURL: 'https://cinelog-2ab20-default-rtdb.firebaseio.com',
    storageBucket: 'cinelog-2ab20.firebasestorage.app',
    measurementId: 'G-SG8L2LXGQ5',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA77UXx9-MgGm2yZSN-LROri9JyGjWzcCA',
    appId: '1:875046596010:ios:03c8238fae5e74167dcfd3',
    messagingSenderId: '875046596010',
    projectId: 'cinelog-2ab20',
    databaseURL: 'https://cinelog-2ab20-default-rtdb.firebaseio.com',
    storageBucket: 'cinelog-2ab20.firebasestorage.app',
    iosBundleId: 'com.example.cinelog',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4mrP9rHavm83Q4jrsvntyg9hD4uuDZX0',
    appId: '1:875046596010:android:6758018d61e0b34a7dcfd3',
    messagingSenderId: '875046596010',
    projectId: 'cinelog-2ab20',
    databaseURL: 'https://cinelog-2ab20-default-rtdb.firebaseio.com',
    storageBucket: 'cinelog-2ab20.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGgrX-w0YmrrxIKqo3zxEs4bcHVraR0AU',
    appId: '1:875046596010:web:0bbca4cb9745644c7dcfd3',
    messagingSenderId: '875046596010',
    projectId: 'cinelog-2ab20',
    authDomain: 'cinelog-2ab20.firebaseapp.com',
    databaseURL: 'https://cinelog-2ab20-default-rtdb.firebaseio.com',
    storageBucket: 'cinelog-2ab20.firebasestorage.app',
    measurementId: 'G-M6EDN6RJWP',
  );

}